CMS/CMS.Web/ViewModels/UploadReferencebooksViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace CMS.Web.ViewModels
{
    public class UploadReferencebooksViewModel
    {
        public int UploadReferencebooksId { get; set; }

        [Required(ErrorMessage = "The Board field is required.")]
        public int BoardId { get; set; }

        [Required(ErrorMessage = "The Class field is required.")]
        public int ClassId { get; set; }

        [Required(ErrorMessage = "The Subject field is required.")]
        public int SubjectId { get; set; }

        public string BoardName { get; set; }

        public string ClassName { get; set; }

        public string SubjectName { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [MinLength(2, ErrorMessage = "The field Title must be a minimum length of '2' and maximum length of '250'.")]
        [MaxLength(250, ErrorMessage = "The field Title must be a minimum length of '2' and maximum length of '250'.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "The Referencebooks Date  field is required.")]
        [DataType(DataType.Date)]
        [Display(Name = "Referencebooks Date")]
        public DateTime UploadDate { get; set; }

        [Display(Name = "File Name")]
        public string FileName { get; set; }

        [Display(Name = "Logo Name")]
        public string LogoName { get; set; }

        [Required]
        [Display(Name = "File")]
        public HttpPostedFileBase FilePath { get; set; }

        [Required]
        [Display(Name = "Logo")]
        public HttpPostedFileBase LogoPath { get; set; }

        [Display(Name = "Board")]
        public IEnumerable<SelectListItem> Boards { get; set; }

        [Display(Name = "Class")]
        public IEnumerable<SelectListItem> Classes { get; set; }

        [Display(Name = "Subject")]
        public IEnumerable<SelectListItem> Subjects { get; set; }

        [Display(Name = "Visible")]
        public bool IsVisible { get; set; }
    }
}

CMS/CMS.Web/Controllers/UploadReferencebooksController.cs
using CMS.Common;
using CMS.Domain.Infrastructure;
using CMS.Domain.Models;
using CMS.Domain.Storage.Projections;
using CMS.Domain.Storage.Services;
using CMS.Web.Logger;
using CMS.Web.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace CMS.Web.Controllers
{
    [Authorize(Roles = Constants.AdminRole + "," + Common.Constants.ClientAdminRole)]
    public class UploadReferencebooksController : BaseController
    {
        readonly IApiService _apiService;
        readonly ILogger _logger;
        readonly IUploadReferencebooksService _uploadReferencebooksService;
        readonly IRepository _repository;

        public UploadReferencebooksController(IApiService apiService, ILogger logger, IUploadReferencebooksService uploadReferencebooksService,
            IRepository repository)
        {
            _apiService = apiService;
            _logger = logger;
            _uploadReferencebooksService = uploadReferencebooksService;
            _repository = repository;
        }
        // GET: UploadNotes
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            var classResult = _apiService.GetClasses();
            var classes = JsonConvert.DeserializeObject<List<ClassProjection>>(classResult);
            var boardResult = _apiService.GetBoards();
            var boards = JsonConvert.DeserializeObject<List<BoardProjection>>(boardResult);


            var classList = (from b in classes
                             select new SelectListItem
                             {
                                 Value = b.ClassId.ToString(),
                                 Text = b.Name
                             }).ToList();

            var boardList = (from b in boards
                             select new SelectListItem
                             {
                                 Value = b.BoardId.ToString(),
                                 Text = b.Name
                             }).ToList();



            return View(new UploadReferencebooksViewModel
            {
                Classes = classList,
                Boards = boardList
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UploadReferencebooksViewModel viewModel)
        {
            var cmsResult = new CMSResult();
            var classResult = _apiService.GetClasses();
            var classes = JsonConvert.DeserializeObject<List<ClassProjection>>(classResult);
            var boardResult = _apiService.GetBoards();
            var boards = JsonConvert.DeserializeObject<List<BoardProjection>>(boardResult);

            var classList = (from b in classes
                             select new SelectListItem
                             {
                                 Value = b.ClassId.ToString(),
                                 Text = b.Name
                             }).ToList();

            var boardList = (from b in boards
                             select new SelectListItem
                             {
                                 Value = b.BoardId.ToString(),
                                 Text = b.Name
                             }).ToList();

            ViewBag.SubjectId = viewModel.SubjectId;
            if (ModelState.IsValid)
            {
                if (!Constants.PdfType.Contains(viewModel.FilePath.ContentType))
                {
                    cmsResult.Results.Add(new Result { Message = "Please choose pdf file.", IsSuccessful = false });
                    _logger.Warn(cmsResult.Results.FirstOrDefault().Message);
                    Warning(cmsResult.Results.FirstOrDefault().Message, true);
                }
                if (!Constants.ImageTypes.Contains(viewModel.LogoPath.ContentType))
                {
                    cmsResult.Results.Add(new Result { Message = "Please choose Image file.", IsSuccessful = false });
                    _logger.Warn(cmsResult.Results.FirstOrDefault().Message);
                    Warning(cmsResult.Results.FirstOrDefault().Message, true);
                }
                string photoPath = "";
                Guid guid = Guid.NewGuid();
                if (viewModel.LogoPath != null)
                    photoPath = string.Format(@"~/Images/{0}/{1}.jpg", Constants.UploadReferencebooksLogo, guid);
                ViewBag.SubjectId = viewModel.SubjectId;
                if (cmsResult.Success)
                {
                    var result = _uploadReferencebooksService.Save(new UploadReferencebooks
                    {
                        BoardName = viewModel.BoardName,
                        ClassName = viewModel.ClassName,
                        SubjectName = viewModel.SubjectName,
                        Title = viewModel.Title,
                        UploadDate = viewModel.UploadDate,
                        FileName = viewModel.FilePath.FileName,
                        LogoName = photoPath,
                        IsVisible = viewModel.IsVisible,
                        ClassId = viewModel.ClassId,
                        BoardId = viewModel.BoardId,
                        SubjectId = viewModel.SubjectId
                    });

                    if (result.Success)
                    {
                        //string folderPath = Server.MapPath(string.Concat("~/PDF/", Constants.UploadNotesPDF));
                        string folderPath = Server.MapPath(string.Concat("~/PDF/", Constants.UploadReferencebooksPDF));
                        if (!Directory.Exists(folderPath))
                        {
                            Directory.CreateDirectory(folderPath);
                        }
                        var pathToSaveQI = Path.Combine(folderPath, string.Format("{0}", viewModel.FilePath.FileName));
                        if (viewModel.FilePath != null)
                            viewModel.FilePath.SaveAs(pathToSaveQI);

                        string LogoPath = Server.MapPath(string.Concat("~/Images/", Constants.UploadReferencebooksLogo));
                        if (!Directory.Exists(LogoPath))
                        {
                            Directory.CreateDirectory(LogoPath);
                        }
                        var pathToSaveLogo = Path.Combine(LogoPath, string.Format("{0}.jpg", guid));
                        if (viewModel.LogoPath != null)
                            viewModel.LogoPath.SaveAs(pathToSaveLogo);

                        Success(result.Results.FirstOrDefault().Message);
                        ModelState.Clear();
                        viewModel = new UploadReferencebooksViewModel();
                    }
                    else
                    {
                        _logger.Warn(result.Results.FirstOrDefault().Message);
                        Warning(result.Results.FirstOrDefault().Message, true);
                    }
                }
            }

            viewModel.Classes = classList;
            viewModel.Boards = boardList;
            return View(viewModel);
        }

        public ActionResult Edit(int id)
        {
            var projection = _uploadReferencebooksService.GetReferencebooksById(id);

            var classResult = _apiService.GetClasses();
            var classes = JsonConvert.DeserializeObject<List<ClassProjection>>(classResult);
            var boardResult = _apiService.GetBoards();
            var boards = JsonConvert.DeserializeObject<List<BoardProjection>>(boardResult);
            var classId = classes.Where(x => x.Name == projection.ClassName).Select(y => y.ClassId).FirstOrDefault();
            var subjectResult = _apiService.GetSubjects(classId);
            var subjects = JsonConvert.DeserializeObject<List<SubjectProjection>>(subjectResult);
            var boardId = boards.Where(x => x.Name == projection.BoardName).Select(y => y.BoardId).FirstOrDefault();
            var subjectId = subjects.Where(x => x.Name == projection.SubjectName).Select(y => y.SubjectId).FirstOrDefault();

            ViewBag.classList = (from b in classes
                                 select new SelectListItem
                                 {
                                     Value = b.ClassId.ToString(),
                                     Text = b.Name
                                 }).ToList();

            ViewBag.boardList = (from b in boards
                                 select new SelectListItem
                                 {
                                     Value = b.BoardId.ToString(),
                                     Text = b.Name
                                 }).ToList();

            ViewBag.subjectList = (from b in subjects
                                   select new SelectListItem
                                   {
                                       Value = b.SubjectId.ToString(),
                                       Text = b.Name
                                   }).ToList();

            if (projection == null)
            {
                _logger.Warn(string.Format("Referencebooks does not Exists {0}."));
                Warning("Referencebooks does not Exists.");
                return RedirectToAction("Index");
            }

            var viewModel = AutoMapper.Mapper.Map<UploadReferencebooksProjection, UploadReferencebooksEditViewModel>(projection);
            ViewBag.ClassId = classId;
            ViewBag.BoardId = boardId;
            ViewBag.SubjectId = subjectId;

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UploadReferencebooksEditViewModel viewModel)
        {
            var cmsResult = new CMSResult();
            var classResult = _apiService.GetClasses();

CMS/CMS.Web/Views/UploadReferencebooks/Create.cshtml
@model CMS.Web.ViewModels.UploadReferencebooksViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Upload Referencebooks</h2>
@using (Html.BeginForm("Create", "UploadReferencebooks", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.BoardName)
    @Html.HiddenFor(m => m.ClassName)
    @Html.HiddenFor(m => m.SubjectName)

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Boards, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BoardId, new SelectList(Model.Boards, "Value", "Text"), "Select Board",
                     new { @class = "form-control", @onchange = "GetBoardName()" })
                @Html.ValidationMessageFor(model => model.BoardId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Classes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ClassId, new SelectList(Model.Classes, "Value", "Text"), "Select Class",
                     new { @class = "form-control", @onchange = "FillSubjects(this.value)" })
                @Html.ValidationMessageFor(model => model.ClassId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Subjects, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SubjectId, new SelectList(Enumerable.Empty<SelectListItem>(),
                   "SubjectId", "Name"), "Select Subject", new { @class = "form-control", @onchange = "GetSubjectName()" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UploadDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UploadDate, new { htmlAttributes = new { @class = "form-control datepicker", @autocomplete = "off", @type = "text", @maxlength = "10", @placeholder = "DD-MM-YYYY" } })
                @Html.ValidationMessageFor(model => model.UploadDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2", @id = "lblFilePath" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FilePath, new { @type = "file", @class = "file input-group-margin", @accept = "application/pdf", @maxFileSize = 123456789 })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LogoPath, htmlAttributes: new { @class = "control-label col-md-2", @id = "lblFilePath" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.LogoPath, new { @type = "file", @class = "file input-group-margin", @accept = "image/*", @maxFileSize = 123456789 })
                @Html.ValidationMessageFor(model => model.LogoPath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsVisible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div class="checkbox checkbox-inline check-box">
                    @Html.EditorFor(model => model.IsVisible)
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to Upload Referencebooks List", "Index")
</div>
@section Scripts{
    <script>
        $(document).ready(function () {

            if ($("#UploadDate").val() == "0001-01-01")
                $("#UploadDate").val('');

            if ($("#ClassId").val() > 0)
                FillSubjects($("#ClassId").val());

            if ('@ViewBag.SubjectId' != "") {
                $("#SubjectId").val(@ViewBag.SubjectId);
            }
        });

        function GetBoardName() {
            $("#BoardName").val(($("#BoardId :selected").text()));
        }

        function GetSubjectName() {
            $("#SubjectName").val(($("#SubjectId :selected").text()));
        }

        function FillSubjects(classId) {
            console.log(classId);
            if (classId != "") {
                $("#ClassName").val(($("#ClassId :selected").text()));
                $.ajax({
                    url: "/Subject/GetSubjects",
                    type: "GET",
                    dataType: "JSON",
                    data: { classId: $("#ClassId").val() },
                    async: false,
                    success: function (data) {
                        $("#SubjectId").html("");
                        $("#SubjectId").append("<option>Select Subject</option>");
                        $.each(data, function (i, sub) {
                            $("#SubjectId").append("<option value='" + sub.SubjectId + "'>" + sub.Name + "</option>");
                        });
                    }, error: function (result) {
                        console.log(result);
                    }
                });
            }
            else {
                $("#SubjectId").html("");
            }
        }
    </script>
}

CMS/CMS.Web/Views/UploadReferencebooks/Delete.cshtml
@model CMS.Web.ViewModels.UploadReferencebooksEditViewModel
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Delete Referencebooks</h2>
<h3>Are you sure you want to delete this?</h3>
<br />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Board")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BoardName)
        </dd>
        <dt>
            @Html.DisplayName("Class")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>
        <dt>
            @Html.DisplayName("Subject")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UploadDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UploadDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FileName)
            <a href='/UploadResult/DownloadPDF?id=@Html.DisplayFor(model => model.UploadReferencebooksId)'>
                <span id="qdel" class="glyphicon glyphicon-download-alt" data-value="1" }></span>
            </a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LogoName)
        </dt>
        <dd>
            <div class="col-md-10">
                <img src="@Url.Content((Model.LogoName))" width="100" height="100" alt="Model.PhotoPath" />
            </div>
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.UploadReferencebooksId)
        @Html.HiddenFor(m => m.Title)
        @Html.HiddenFor(m => m.FileName)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Upload Referencebooks List", "Index")
        </div>
    }
</div>

CMS/CMS.Web/Views/UploadReferencebooks/Edit.cshtml
@model CMS.Web.ViewModels.UploadReferencebooksEditViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Edit Referencebooks</h2>
@using (Html.BeginForm("Edit", "UploadReferencebooks", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.BoardName)
    @Html.HiddenFor(m => m.ClassName)
    @Html.HiddenFor(m => m.SubjectName)
    @Html.HiddenFor(m => m.UploadReferencebooksId)
    @Html.HiddenFor(m => m.FileName)
    @Html.HiddenFor(m => m.LogoName)
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Boards, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.BoardId, new SelectList(ViewBag.boardList, "Value", "Text"), new { @class = "form-control", @onchange = "GetBoardName()" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Classes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ClassId, new SelectList(ViewBag.classList, "Value", "Text"), new { @class = "form-control", @onchange = "FillSubjects(this.value)" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Subjects, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SubjectId, new SelectList(ViewBag.subjectList, "Value", "Text"), new { @class = "form-control", @onchange = "GetSubjectName()" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UploadDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UploadDate, new { htmlAttributes = new { @class = "form-control datepicker", @autocomplete = "off", @type = "text", @maxlength = "10", @placeholder = "DD-MM-YYYY" } })
                @Html.ValidationMessageFor(model => model.UploadDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FileName)
                <a href='/UploadResult/DownloadPDF?id=@Html.DisplayFor(model => model.UploadReferencebooksId)'>
                    <span id="qdel" class="glyphicon glyphicon-download-alt" data-value="1" }></span>
                </a>
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2", @id = "lblFilePath" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FilePath, new { @type = "file", @class = "file input-group-margin", @accept = "application/pdf", @maxFileSize = 123456789 })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LogoPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content((Model.LogoName))" width="100" height="100" alt="Model.PhotoPath" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LogoPath, htmlAttributes: new { @class = "control-label col-md-2", @id = "lblPhotoFilePath" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.LogoPath, new { @type = "file", @class = "inline", @accept = ".png,.jpg,.jpeg,.gif" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsVisible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox checkbox-inline">
                    @Html.EditorFor(model => model.IsVisible)
                    @Html.ValidationMessageFor(model => model.IsVisible, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to Upload Referencebooks List", "Index")
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            if ($("#ClassId").val() > 0)
                FillSubjects($("#ClassId").val());

            if ('@ViewBag.SubjectId' != "")
                $("#SubjectId").val(@ViewBag.SubjectId);
        });

        function GetBoardName() {
            $("#BoardName").val(($("#BoardId :selected").text()));
        }

        function GetSubjectName() {
            $("#SubjectName").val(($("#SubjectId :selected").text()));
        }

        function FillSubjects(classId) {
            if (classId != "") {
                $("#ClassName").val(($("#ClassId :selected").text()));
                $.ajax({
                    url: "/UploadResult/GetSubjects",
                    type: "GET",
                    dataType: "JSON",
                    data: { classId: $("#ClassId").val() },
                    async: false,
                    success: function (data) {
                        $("#SubjectId").html("");
                        $.each(data, function (i, sub) {
                            $("#SubjectId").append("<option value='" + sub.SubjectId + "'>" + sub.Name + "</option>");
                        });
                    }
                });
            }
            else {
                $("#SubjectId").html("");
            }
        }
    </script>
}

CMS/CMS.Web/Views/UploadReferencebooks/Index.cshtml
@model IEnumerable<CMS.Web.ViewModels.UploadReferencebooksViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Referencebooks List</h2>
<p>
    @Html.ActionLink("Upload New Referencebooks", "Create")
</p>
<div class="panel panel-default">
    <div class="panel-body">
        @Html.Partial("_MVCGridToolbar", new CMS.Web.Models.MVCGridToolbarModel()
   {
       MVCGridName = "UploadReferencebooksGrid",
       PageSize = true,
       ColumnVisibility = false,
       Export = false,
       GlobalSearch = false
   })
        @Html.MVCGrid("UploadReferencebooksGrid")
    </div>
</div>