CMS/CMS.Web/Controllers/StudentClassTimetableController.cs
using CMS.Common;
using CMS.Domain.Infrastructure;
using CMS.Domain.Models;
using CMS.Domain.Storage.Projections;
using CMS.Domain.Storage.Services;
using CMS.Web.Helpers;
using CMS.Web.Logger;
using CMS.Web.Models;
using CMS.Web.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Hosting;
using System.Web.Mvc;


namespace CMS.Web.Controllers
{
    [Authorize(Roles = Common.Constants.AdminRole + "," + Common.Constants.BranchAdminRole + "," + Common.Constants.ClientAdminRole)]
    public class StudentClassTimetableController : BaseController
    {
        readonly IApiService _apiService;
        readonly IStudentTimetableService _studentTimetableService;
        readonly ILogger _logger;
        readonly IRepository _repository;
        readonly IBranchService _branchService;
        readonly IStudentService _studentService;
        readonly IBatchService _batchService;
        readonly IClassService _classService;
        readonly IAspNetRoles _aspNetRolesService;
        readonly IBranchAdminService _branchAdminService;
        readonly IEmailService _emailService;
        readonly ISendNotificationService _sendNotificationService;

        public StudentClassTimetableController(IApiService apiService, IStudentTimetableService studentTimetableService, ILogger logger,
            IRepository repository, IBranchService branchService,
            IStudentService studentService, IBatchService batchService,
            IClassService classService, IAspNetRoles aspNetRolesService,
            IBranchAdminService branchAdminService, IEmailService emailService, ISendNotificationService sendNotificationService)
        {
            _apiService = apiService;
            _studentTimetableService = studentTimetableService;
            _logger = logger;
            _repository = repository;
            _branchService = branchService;
            _studentService = studentService;
            _batchService = batchService;
            _classService = classService;
            _aspNetRolesService = aspNetRolesService;
            _branchAdminService = branchAdminService;
            _emailService = emailService;
            _sendNotificationService = sendNotificationService;
        }
        // GET: StudentTimetable
        public ActionResult Index()
        {
            var roleUserId = User.Identity.GetUserId();
            var roles = _aspNetRolesService.GetCurrentUserRole(roleUserId);
            var projection = roles == "BranchAdmin" ? _branchAdminService.GetBranchAdminById(roleUserId) : null;
            if (roles == "Admin" || roles=="Client")
            {
                ViewBag.userId = 0;
            }
            else
            {
                ViewBag.userId = projection.BranchId;
            }
            return View();
        }

        public ActionResult Create()
        {
            var roleUserId = User.Identity.GetUserId();
            var roles = _aspNetRolesService.GetCurrentUserRole(roleUserId);

            if (roles == "Admin" || roles=="Client")
            {
                var branchList = (from b in _branchService.GetAllBranches()
                                  select new SelectListItem
                                  {
                                      Value = b.BranchId.ToString(),
                                      Text = b.Name
                                  }).ToList();

                ViewBag.BranchId = 0;
                ViewBag.CurrentUserRole = roles;

                return View(new StudentTimetableViewModel
                {
                    Branches = branchList,
                    CurrentUserRole = roles
                });
            }
            else if (roles == "BranchAdmin")
            {
                var projection = _branchAdminService.GetBranchAdminById(roleUserId);
                ViewBag.BranchId = projection.BranchId;
                var classList = (from c in _studentService.GetStudentsByBranchId(projection.BranchId)
                                 select new SelectListItem
                                 {
                                     Value = c.ClassId.ToString(),
                                     Text = c.ClassName
                                 }).ToList();
                ViewBag.CurrentUserRole = roles;
                return View(new StudentTimetableViewModel
                {
                    CurrentUserRole = roles,
                    BranchId = projection.BranchId,
                    BranchName = projection.BranchName,
                    Classes = classList,
                    SelectedBranches = projection.BranchId.ToString()
                });
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentTimetableViewModel viewModel)
        {
            var roleUserId = User.Identity.GetUserId();
            var roles = _aspNetRolesService.GetCurrentUserRole(roleUserId);
            var cmsResult = new CMSResult();

            if (ModelState.IsValid)
            {
                string fileName = "";
                Guid guid = Guid.NewGuid();
                if (viewModel.FilePath != null)
                {
                    if (viewModel.AttachmentDescription == null)
                    {
                        _logger.Warn("Please enter attachment description.");
                        Warning("Please enter attachment description.", true);
                        ReturnViewModel(viewModel, roles, roleUserId);
                        return View(viewModel);
                    }
                    else if (Common.Constants.ImageTypes.Contains(viewModel.FilePath.ContentType) ||
                        Common.Constants.PdfType.Contains(viewModel.FilePath.ContentType))
                    {
                        if (viewModel.FilePath != null)
                            if (Common.Constants.ImageTypes.Contains(viewModel.FilePath.ContentType))
                                fileName = string.Format("{0}.jpg", guid);
                            else
                                fileName = string.Format("{0}.pdf", guid);
                    }
                    else
                    {
                        _logger.Warn("Please choose either a JPEG, JPG, PNG image or pdf file.");
                        Warning("Please choose either a JPEG, JPG, PNG image or pdf file", true);
                        ReturnViewModel(viewModel, roles, roleUserId);
                        return View(viewModel);
                    }
                }
                var description = viewModel.Description.Replace("\r\n", "<br />");
                viewModel.Description = description;
                var studentClassTimetable = new StudentTimetable
                {
                    Description = viewModel.Description,
                    SelectedBranches = viewModel.SelectedBranches != null ? viewModel.SelectedBranches : "",
                    SelectedClasses = viewModel.SelectedClasses != null ? viewModel.SelectedClasses : "",
                    SelectedBatches = viewModel.SelectedBatches != null ? viewModel.SelectedBatches : "",
                    FileName = fileName,
                    Category = Common.Enums.TimetableCategory.ClassTimetable,
                    AttachmentDescription = viewModel.AttachmentDescription != null ? viewModel.AttachmentDescription : "",
                    StudentTimetableDate = viewModel.StudentTimetableDate
                };
                var result = _studentTimetableService.Save(studentClassTimetable);
                
                if (result.Success)
                {
                    var studentClassTimetableId = studentClassTimetable.StudentTimetableId;

                    if (viewModel.FilePath != null)
                    {
                        var pathToSaveQI = "";
                        string folderPath = Server.MapPath(string.Concat("~/PDF/", Common.Constants.StudentTimeTableFile));
                        if (!Directory.Exists(folderPath))
                        {
                            Directory.CreateDirectory(folderPath);
                        }

                        if (Common.Constants.ImageTypes.Contains(viewModel.FilePath.ContentType))
                            pathToSaveQI = Path.Combine(folderPath, string.Format("{0}.jpg", guid));
                        else
                            pathToSaveQI = Path.Combine(folderPath, string.Format("{0}.pdf", guid));

                        if (viewModel.FilePath != null)
                            viewModel.FilePath.SaveAs(pathToSaveQI);
                    }

                    var sendAppNotification = SendAppNotification(viewModel, studentClassTimetableId);

                    if (roles == "BranchAdmin")
                        SendTimetable(viewModel);

                    Success(result.Results.FirstOrDefault().Message + "<br />" + sendAppNotification.Results[0].Message);
                    ModelState.Clear();
                    viewModel = new StudentTimetableViewModel();
                }
                else
                {
                    _logger.Warn(result.Results.FirstOrDefault().Message);
                    Warning(result.Results.FirstOrDefault().Message, true);
                }
            }
            ReturnViewModel(viewModel, roles, roleUserId);
            return View(viewModel);
        }

        public void ReturnViewModel(StudentTimetableViewModel viewModel, string roles, string roleUserId)
        {
            if (roles == "Admin" || roles=="Client")
            {

CMS/CMS.Web/Views/StudentClassTimetable/Create.cshtml
@model CMS.Domain.Storage.Projections.StudentTimetableViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create Class Timetable</h2>
@using (Html.BeginForm("Create", "StudentClassTimetable", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.SelectedBatches)
    @Html.HiddenFor(m => m.SelectedClasses)
    @Html.HiddenFor(m => m.SelectedBranches)
    @Html.HiddenFor(m => m.CurrentUserRole)

    <div class="form-horizontal">
        <div id="message">
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (Model.CurrentUserRole == "Admin")
        {
            <div class="form-group">
                @Html.LabelFor(m => m.Branches, htmlAttributes: new { @class = "control-label col-md-2 asterisk_input", @id = "lblBranch" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.BranchId, new SelectList(Model.Branches, "Value", "Text"),
                     new { @class = "form-control", @onchange = "FillClasses(this.value)", @multiple = "multiple" })
                    @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" id="classDetail">
                @Html.LabelFor(m => m.ClassId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ClassId, new SelectList(Enumerable.Empty<SelectListItem>(),
                   "ClassId", "Name"), new { @class = "form-control", @onchange = "FillBatches(this.value)", @multiple = "multiple" })
                </div>
            </div>
        }
        else if (Model.CurrentUserRole == "BranchAdmin")
        {
            <div class="form-group">
                @Html.LabelFor(m => m.BranchName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(m => m.BranchName, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       @readonly = "readonly"
                   }
               })
                    @Html.HiddenFor(m => m.BranchId)
                </div>
            </div>

            <div class="form-group" id="classDetail">
                @Html.LabelFor(m => m.Classes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ClassId, new SelectList(Model.Classes, "Value", "Text"), "Select Class",
                   new { @class = "form-control", @onchange = "FillBatches(this.value)", @multiple = "multiple" })
                </div>
            </div>
        }

        <div class="form-group" id="batchDetail">
            @Html.LabelFor(m => m.BatchId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BatchId, new SelectList(Enumerable.Empty<SelectListItem>(), "BatchId", "Name"),
                   new { @class = "form-control", @multiple = "multiple", @onchange = "getSelectedBatches()" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2 asterisk_input", @id = "lblDescription" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StudentTimetableDate, htmlAttributes: new { @class = "control-label col-md-2 asterisk_input", @id = "lblDate" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentTimetableDate, new { htmlAttributes = new { @class = "form-control datepicker", autocomplete = "off", @type = "text", @maxlength = "10", @placeholder = "DD-MM-YYYY" } })
                @Html.ValidationMessageFor(model => model.StudentTimetableDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2", @id = "lblFilePath" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FilePath, new { @type = "file", @class = "file input-group-margin", @accept = "image/jpeg,image/gif,image/png,application/pdf,image/x-eps" })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AttachmentDescription, htmlAttributes: new { @class = "control-label col-md-2", @id = "lblDescription" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AttachmentDescription, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.AttachmentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.Label("(By default app notification send to parent)")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="send" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Class Timetable List", "Index")
</div>
@section Scripts {
    <script>

        $(document).ready(function () {
            $("#AttachmentDescription").val('');
            $('#Description').on('change', function () {
                RequiredValidation('#v', '#lblDescription')
            });

            $("#StudentTimetableDate").on('change', function () {
                RequiredValidation('#v', '#lblDate')
            });

            $('#BranchId').on('change', function () {
                RequiredValidation('#v', '#lblBranch')
            });

            if ($("#SelectedBranches").val() != "") {
                if ($("#CurrentUserRole").val() == "Admin") {
                    $('#BranchId')
                    .multiselect({
                        allSelectedText: 'All',
                        includeSelectAllOption: true
                    });

                    var arr = $("#SelectedBranches").val().split(',');
                    arr.forEach(function (i) {
                        $("#BranchId").multiselect('select', i)
                    });
                }
                getCountOnBranch();
            }

            if ($("#SelectedClasses").val() != "") {
                $('#ClassId')
                .multiselect({
                    allSelectedText: 'All',
                    includeSelectAllOption: true
                });

                var arr = $("#SelectedClasses").val().split(',');
                arr.forEach(function (i) {
                    console.log(i);
                    $("#ClassId").multiselect('select', i)
                });
                getCountOnClass();
            }

            if ($("#SelectedBatches").val() != "") {
                $('#BatchId')
                .multiselect({
                    allSelectedText: 'All',
                    includeSelectAllOption: true
                });

                var arr = $("#SelectedBatches").val().split(',');
                arr.forEach(function (i) {
                    $("#BatchId").multiselect('select', i)
                });
            }

            $('#ClassId').multiselect({
                includeSelectAllOption: true
            });

            $('#BatchId').multiselect({
                includeSelectAllOption: true
            });

            if ($("#CurrentUserRole").val() == "Admin") {
                $('#BranchId').multiselect({
                    includeSelectAllOption: true
                });
            }

            $('#FilePath').on('change', function () {
                if ($("#FilePath").val() != "") {
                    console.log("ok");
                    $("#AttachmentDescription").removeAttr("readonly");
                }
                if ($("#FilePath").val() == "") {
                    console.log("blank");
                    $("#AttachmentDescription").val('');
                    $("#AttachmentDescription").attr("readonly", "readonly");
                }
            });
        });

        function getSelectedBatches() {
            var selected = $("#BatchId").find("option:selected");
            var arrSelected = [];
            selected.each(function () {
                arrSelected.push($(this).val());
            });
            var selectedSubject = arrSelected.toString();
            $("#SelectedBatches").val(selectedSubject);
        }

        function FillClasses(branchId) {

            var selected = $("#BranchId").find("option:selected");
            var arrSelected = [];
            selected.each(function () {
                arrSelected.push($(this).val());
            });
            var selectedBranch = arrSelected.toString();
            $("#SelectedBranches").val(selectedBranch);
            if ($("#BranchId option:selected").length == 0) {
                DestroyBatches();
                DestroyClasses();
            }
            else {
                getCountOnBranch();
                DestroyBatches();
            }
        }

        function getCountOnBranch() {
            $.ajax({
                url: '/StudentTimetable/GetClassesByMultipleBranches',
                type: "GET",
                dataType: "JSON",
                data: { selectedBranch: $("#SelectedBranches").val() },
                async: false,
                success: function (data) {
                    $("#ClassId").html(""); // clear before appending new list
                    $("#ClassId").multiselect('destroy');
                    $("#BatchId").multiselect('destroy');
                    $.each(data.classes, function (i, cls) {
                        $("#ClassId").append(
                            $('<option></option>').val(cls.ClassId).html(cls.ClassName));
                    });

                    $('#ClassId')
                    .multiselect({
                        allSelectedText: 'All',
                        includeSelectAllOption: true
                    });
                }
            });
        }

        function getCountOnClass() {
            if ($("#SelectedClasses").val() != "") {
                $.ajax({
                    url: '/StudentTimetable/GetBatchesByClassId',
                    type: "GET",
                    dataType: "JSON",
                    data: { selectedClasses: $("#SelectedClasses").val(), selectedBranch: $("#SelectedBranches").val() },
                    success: function (data) {
                        var select = $("#BatchId");
                        select.children().remove();
                        $("#BatchId").html(""); // clear before appending new list
                        $("#BatchId").multiselect('destroy');
                        $.each(data.batches, function (i, sub) {
                            $("#BatchId").append("<option value='" + sub.BatchId + "'>" + sub.BatchName + "</option>");
                        });
                        //$("#BatchId").multiselect('rebuild');
                        $('#BatchId')
                        .multiselect({
                            allSelectedText: 'All',
                            includeSelectAllOption: true
                        });
                        if ($("#SelectedBatches").val() != "") {
                            var arr = $("#SelectedBatches").val().split(',');
                            arr.forEach(function (i) {
                                $("#BatchId").multiselect('select', i)
                            });
                        }
                    }
                });
            }
        }

        function FillBatches(classId) {
            var selected = $("#ClassId").find("option:selected");
            var arrSelected = [];
            selected.each(function () {
                arrSelected.push($(this).val());
            });
            var selectedClass = arrSelected.toString();
            $("#SelectedClasses").val(selectedClass);
            $("#SelectedBatches").val("");
            if ($("#SelectedClasses").val() == "") {
                DestroyBatches();
            }
            else {
                getCountOnClass();
            }
        }

        function DestroyBatches() {
            $("#BatchId").html("");
            $("#BatchId").multiselect('destroy');
            $("#BatchId").multiselect('rebuild');
        }

        function DestroyClasses() {
            $("#ClassId").html("");
            $("#ClassId").multiselect('destroy');
            $("#ClassId").multiselect('rebuild');
        }
    </script>
    @Scripts.Render("~/bundles/StudentJS")
    @Styles.Render("~/Content/StudentCSS")
}

CMS/CMS.Web/Views/StudentClassTimetable/Delete.cshtml
@model CMS.Web.ViewModels.StudentTimetableEditViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete Class Timetable</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SelectedBranches)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectedBranches)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.SelectedClasses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectedClasses)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.SelectedBatches)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectedBatches)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <br />
        @if (ViewBag.fileName != "" && ViewBag.fileName != null)
            {
            <dt>
                @Html.DisplayNameFor(model => model.FileName)
            </dt>
            <dd>
                <a href='@Url.Action("DownloadPDF", "StudentTimetable", new { id = Model.StudentTimetableId })' target="_blank"><span class='glyphicon glyphicon-download-alt'></span></a>
            </dd>
            <br />
            <dt>
                @Html.DisplayNameFor(model => model.AttachmentDescription)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AttachmentDescription)
            </dd>
            <br />
        }        
        <dt>
            @Html.DisplayNameFor(model => model.StudentTimetableDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentTimetableDate)
        </dd>
        <br />
    </dl>

    @using (Html.BeginForm())
    {

        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Description)
        @Html.HiddenFor(x => x.StudentTimetableId)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Class Timetable List", "Index")
        </div>
    }
</div>

CMS/CMS.Web/Views/StudentClassTimetable/Edit.cshtml
@model CMS.Web.ViewModels.StudentTimetableEditViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit Student Class Timetable</h2>
@using (Html.BeginForm("Edit", "StudentClassTimetable", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.StudentTimetableId)
    @Html.HiddenFor(m => m.FileName)
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedBranches, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectedBranches, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @readonly = "readonly" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedClasses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectedClasses, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedBatches, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelectedBatches, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @readonly = "readonly" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StudentTimetableDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.StudentTimetableDate, new { htmlAttributes = new { @class = "form-control datepicker", autocomplete = "off", @type = "text", @maxlength = "10", @placeholder = "DD-MM-YYYY" } })
                @Html.ValidationMessageFor(model => model.StudentTimetableDate, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (ViewBag.fileName != "" && ViewBag.fileName != null)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2", @id = "lblFilePath" })
                <div class="col-md-10">

                    <a href='@Url.Action("DownloadPDF", "StudentTimetable", new { id = Model.StudentTimetableId })' target="_blank"><span class='glyphicon glyphicon-download-alt'></span></a>

                </div>
            </div>
        }
        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2", @id = "lblFilePath" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FilePath, new { @type = "file", @class = "file input-group-margin", @accept = "image/jpeg,image/gif,image/png,application/pdf,image/x-eps" })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AttachmentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AttachmentDescription, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.AttachmentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Class Timetable List", "Index")
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#FilePath').on('change', function () {
                if ($("#FilePath").val() != "") {
                    $("#AttachmentDescription").removeAttr("readonly");
                }
                if ($("#FilePath").val() == "") {
                    $("#AttachmentDescription").attr("readonly", "readonly");
                }
            });
        });
    </script>
}

