CMS/CMS.Web/ViewModels/ClassViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CMS.Web.ViewModels
{
    public class ClassViewModel
    {
        public int ClassId { get; set; }

        //[RegularExpression("^[a-zA-Z0-9]+[0-9]*[a-zA-Z\\- ]+$", ErrorMessage = "Class Name should contain 0-9, a-z, -, A-Z.")]
        [Required]
        [MaxLength(50, ErrorMessage = "The field Class Name must be a minimum length of '1' and maximum length of '50'.")]
        [MinLength(1, ErrorMessage = "The field Class Name must be a minimum length of '1' and maximum length of '50'.")]
        [Display(Name = "Class Name")]
        public string Name { get; set; }
    }
}

CMS/CMS.Web/Controllers/ClassController.cs
using CMS.Domain.Infrastructure;
using CMS.Domain.Models;
using CMS.Domain.Storage.Projections;
using CMS.Domain.Storage.Services;
using CMS.Web.Helpers;
using CMS.Web.Logger;
using CMS.Web.Models;
using CMS.Web.ViewModels;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace CMS.Web.Controllers
{
    [Authorize(Roles = Common.Constants.AdminRole + "," + Common.Constants.BranchAdminRole + "," + Common.Constants.ClientAdminRole)]
    public class ClassController : BaseController
    {
        readonly IClassService _classService;
        readonly ILogger _logger;
        readonly IRepository _repository;
        readonly IEmailService _emailService;
        readonly IAspNetRoles _aspNetRolesService;
        readonly IBranchAdminService _branchAdminService;

        public ClassController(IClassService classService, ILogger logger, IRepository repository, IEmailService emailService, IAspNetRoles aspNetRolesService, IBranchAdminService branchAdminService)
        {
            _classService = classService;
            _logger = logger;
            _repository = repository;
            _emailService = emailService;
            _aspNetRolesService = aspNetRolesService;
            _branchAdminService = branchAdminService;
        }

        public ActionResult Index()
        {
            //var classes = _classService.GetClasses().ToList();
            //var viewModelList = AutoMapper.Mapper.Map<List<ClassProjection>, ClassViewModel[]>(classes);
            //return View(viewModelList);
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClassViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _classService.Save(new Class { Name = viewModel.Name });
                if (result.Success)
                {
                    var bodySubject = "Web portal changes - Class Create";
                    SendMailToAdmin(result.Results.FirstOrDefault().Message, bodySubject);
                    Success(result.Results.FirstOrDefault().Message);
                    ModelState.Clear();
                    viewModel = new ClassViewModel();
                }
                else
                {
                    _logger.Warn(result.Results.FirstOrDefault().Message);
                    Warning(result.Results.FirstOrDefault().Message, true);
                }
            }
            viewModel = new ClassViewModel();
            return View(viewModel);
        }

        public ActionResult Edit(int id)
        {
            var projection = _classService.GetClassById(id);
            if (projection == null)
            {
                _logger.Warn(string.Format("Class does not Exists {0}.", id));
                Warning("Class does not Exists.");
                return RedirectToAction("Index");
            }
            var viewModel = AutoMapper.Mapper.Map<ClassProjection, ClassViewModel>(projection);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClassViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var cls = _repository.Project<Class, bool>(classes => (from clss in classes where clss.ClassId == viewModel.ClassId select clss).Any());

                if (!cls)
                {
                    _logger.Warn(string.Format("Class not exists '{0}'.", viewModel.Name));
                    Danger(string.Format("Class not exists '{0}'.", viewModel.Name));
                }

                var result = _classService.Update(new Class { ClassId = viewModel.ClassId, Name = viewModel.Name });
                if (result.Success)
                {
                    var bodySubject = "Web portal changes - Class updated";
                    SendMailToAdmin(result.Results.FirstOrDefault().Message, bodySubject);
                    Success(result.Results.FirstOrDefault().Message);
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }
                else
                {
                    _logger.Warn(result.Results.FirstOrDefault().Message);
                    Warning(result.Results.FirstOrDefault().Message, true);
                }
            }
            return View(viewModel);
        }

        public ActionResult Delete(int id)
        {
            var projection = _classService.GetClassById(id);
            if (projection == null)
            {
                _logger.Warn(string.Format("Class does not Exists {0}.", id));
                Warning("Class does not Exists.");
                return RedirectToAction("Index");
            }
            var viewModel = AutoMapper.Mapper.Map<ClassProjection, ClassViewModel>(projection);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ClassViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                var result = _classService.Delete(viewModel.ClassId);
                if (result.Success)
                {
                    var bodySubject = "Web portal changes - Class Delete";
                    SendMailToAdmin(result.Results.FirstOrDefault().Message, bodySubject);
                    Success(result.Results.FirstOrDefault().Message);
                    ModelState.Clear();
                }
                else
                {
                    _logger.Warn(result.Results.FirstOrDefault().Message);
                    Warning(result.Results.FirstOrDefault().Message, true);
                }
            }
            return RedirectToAction("Index");
        }

        //public ActionResult GetClasses()
        //{
        //    var subjects = _classService.GetClasses().Select(x => new { output = new { id = x.ClassId, name = x.Name }, selected = "" });
        //    return Json(subjects, JsonRequestBehavior.AllowGet);
        //}

        public ActionResult GetClasses()
        {
            var subjects = _classService.GetClasses().Select(x => new { x.ClassId, x.Name });
            return Json(subjects, JsonRequestBehavior.AllowGet);
        }

        public void SendMailToAdmin(string message, string bodySubject)
        {
            var roleUserId = User.Identity.GetUserId();
            var roles = _aspNetRolesService.GetCurrentUserRole(roleUserId);
            if (roles == "BranchAdmin")
            {
                var branchAdmin = _branchAdminService.GetBranchAdminById(roleUserId);
                var branchName = branchAdmin.BranchName;

                string body = string.Empty;
                using (StreamReader reader = new StreamReader(Server.MapPath("~/MailDesign/CommonMailDesign.html")))
                {
                    body = reader.ReadToEnd();
                }
                body = body.Replace("{BranchName}", branchName);
                body = body.Replace("{ModuleName}", message);
                body = body.Replace("{BranchAdminEmail}", "( " + User.Identity.GetUserName() + " )");
                var emailMessage = new MailModel
                {
                    Body = body,
                    Subject = bodySubject,
                    IsBranchAdmin = true
                };
                _emailService.Send(emailMessage);
            }
        }
    }
}

CMS/CMS.Web/Views/Class/Create.cshtml
@model CMS.Web.ViewModels.ClassViewModel

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Create";
}

<h2>Create Class</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2 asterisk_input", @id = "lblName" })
            <span class="control-label glyphicon glyphicon-info-sign" title="Class name, will be required while create subject, student
             & masterfee.." id="tooltipName"></span>
            <div class="col-md-3">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Classes List", "Index")
</div>

@section Scripts {
    <script>
        $("#tooltipName").tooltip({ track: true });
        $('#Name').on('change', function () {
            RequiredValidation('#Name', '#lblName')
        });
    </script>
}


CMS/CMS.Web/Views/Class/Delete.cshtml
@model CMS.Web.ViewModels.ClassViewModel

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Delete";
}
<br />
<h2>Delete Class</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    @using (Html.BeginForm())
    {
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>


        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ClassId)
        @Html.HiddenFor(model => model.Name)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Classes List", "Index")
        </div>
    }
</div>

CMS/CMS.Web/Views/Class/Edit.cshtml
@model CMS.Web.ViewModels.ClassViewModel

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Edit";
}

<h2>Edit Class</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ClassId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Classes List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CMS/CMS.Web/Views/Class/Index.cshtml
@model IEnumerable<CMS.Web.ViewModels.ClassViewModel>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Index";
}
<h2>Class List</h2>
@section scripts{
    @*<script type="text/javascript">

            //$("#dialog-confirm").hide();
            $(function () {
                $(".deleteConfirm").click(function (e) {
                    e.preventDefault();
                    var url = $(this).attr('href');
                    $("#dialog-confirm").dialog({
                        resizable: false,
                        height: 220,
                        width: 475,
                        modal: true,
                        buttons: {
                            "OK": function () {

                                //$(this).dialog("close");

                                window.location.href = url;  //<-------
                            },
                            "Cancel": function () {
                                $(this).dialog("close");
                            }
                        }
                    });
                    $("#dialog-confirm").dialog("open"); // <------- open dialog this way.
                });
            });
        </script>*@

    <script>
        $('#myModal').on('shown.bs.modal', function () {
            $('#myInput').focus()
        })
    </script>
}
<br />

<p>
    @Html.ActionLink("Create New Class", "Create")
</p>
<div id="dialog-confirm"></div>
<div class="well">
    <div class="form-inline">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Class Name"
                   data-mvcgrid-type="filter" data-mvcgrid-option="ClassName" />
        </div>
        <button type="button" class="btn btn-default" data-mvcgrid-apply-filter="click">Search</button>
        <input type="submit" value="Reset" id="Submit" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Class")'" />
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        @* Show code from index page in  mvc grid toolbar *@
        @Html.Partial("_MVCGridToolbar", new CMS.Web.Models.MVCGridToolbarModel()
   {
       MVCGridName = "ClassGrid",
       PageSize = true,
       ColumnVisibility = true,
       Export = true,
       GlobalSearch = false
   })
        @Html.MVCGrid("ClassGrid")
    </div>
</div>